import { createClient } from "npm:@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Content-Type":"application/json"};
const BASE="https://bankaccountdata.gocardless.com/api/v2";
const out=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:cors});
async function token(){const id=Deno.env.get("GOCARDLESS_SECRET_ID"),key=Deno.env.get("GOCARDLESS_SECRET_KEY");if(!id||!key)throw Error("GOCARDLESS_SECRET_ID / GOCARDLESS_SECRET_KEY fehlen");const r=await fetch(`${BASE}/token/new/`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({secret_id:id,secret_key:key})});if(!r.ok)throw Error(await r.text());return (await r.json()).access;}
async function gc(t:string,p:string,o:RequestInit={}){const r=await fetch(`${BASE}${p}`,{...o,headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json",...(o.headers||{})}});const tx=await r.text();let d:any;try{d=JSON.parse(tx)}catch{d={raw:tx}}if(!r.ok)throw Error(d?.detail||d?.summary||`GoCardless HTTP ${r.status}`);return d;}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const ah=req.headers.get("Authorization");if(!ah?.startsWith("Bearer "))return out({error:"Nicht angemeldet"},401);const url=Deno.env.get("SUPABASE_URL")!,pk=Deno.env.get("SUPABASE_ANON_KEY")||Deno.env.get("SUPABASE_PUBLISHABLE_KEY")||"";const uc=createClient(url,pk,{global:{headers:{Authorization:ah}}});const {data:{user},error}=await uc.auth.getUser();if(error||!user)return out({error:"Ungültige Sitzung"},401);const b=await req.json().catch(()=>({}));const a=b.action,t=await token();const admin=createClient(url,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||Deno.env.get("SUPABASE_SECRET_KEY")||"");
if(a==="institutions")return out(await gc(t,`/institutions/?country=${encodeURIComponent(String(b.country||"de").toLowerCase())}`));
if(a==="create-requisition"){const d=await gc(t,"/requisitions/",{method:"POST",body:JSON.stringify({redirect:String(b.redirect),institution_id:String(b.institution_id),reference:user.id,user_language:"DE",account_selection:true,redirect_immediate:true})});const {data:c,error:e}=await admin.from("open_banking_connections").insert({user_id:user.id,requisition_id:d.id,institution_id:b.institution_id,institution_name:b.institution_name||null,institution_logo:b.institution_logo||null,status:d.status||"CR"}).select().single();if(e)throw e;return out({connection_id:c.id,requisition_id:d.id,link:d.link,status:d.status});}
if(a==="get-accounts"){const cid=String(b.connection_id),rid=String(b.requisition_id);const {data:c}=await uc.from("open_banking_connections").select("*").eq("id",cid).eq("requisition_id",rid).single();if(!c)return out({error:"Verbindung nicht gefunden"},404);const r=await gc(t,`/requisitions/${encodeURIComponent(rid)}/`);const accounts=[];for(const id of (r.accounts||[])){const d=await gc(t,`/accounts/${encodeURIComponent(id)}/`);accounts.push({provider_account_id:id,iban:d.iban||null,account_name:d.name||d.bban||"Bankkonto",owner_name:d.owner_name||null,institution_id:d.institution_id||c.institution_id});await admin.from("open_banking_accounts").upsert({user_id:user.id,connection_id:cid,provider_account_id:id,iban:d.iban||null,account_name:d.name||d.bban||"Bankkonto",owner_name:d.owner_name||null,institution_id:d.institution_id||c.institution_id,selected:true},{onConflict:"user_id,provider_account_id"});}await admin.from("open_banking_connections").update({status:r.status||"LN",updated_at:new Date().toISOString()}).eq("id",cid).eq("user_id",user.id);return out({status:r.status,accounts});}
if(a==="sync"){const cid=String(b.connection_id),ids=Array.isArray(b.account_ids)?b.account_ids:[];const {data:c}=await uc.from("open_banking_connections").select("*").eq("id",cid).eq("user_id",user.id).single();if(!c)return out({error:"Verbindung nicht gefunden"},404);const {data:accounts}=await uc.from("open_banking_accounts").select("*").eq("connection_id",cid).eq("user_id",user.id).in("provider_account_id",ids.length?ids:["__none__"]);const inserted=[];for(const acc of accounts||[]){const d=await gc(t,`/accounts/${encodeURIComponent(acc.provider_account_id)}/transactions/`);for(const x of (d?.transactions?.booked||[])){const amount=Number(x?.transactionAmount?.amount);if(!Number.isFinite(amount))continue;const pid=x.transactionId||[x.bookingDate||"",x.transactionAmount?.amount||"",x.remittanceInformationUnstructured||"",x.creditorName||x.debtorName||""].join("|");const desc=x.remittanceInformationUnstructured||x.remittanceInformationUnstructuredArray?.join(" ")||x.creditorName||x.debtorName||"Bankbuchung";const row={user_id:user.id,open_banking_account_id:acc.id,provider_transaction_id:pid,booking_date:x.bookingDate||null,value_date:x.valueDate||null,description:desc,counterparty:x.creditorName||x.debtorName||null,amount,currency:x.transactionAmount?.currency||"EUR",raw:x};const {data:created,error:e}=await admin.from("open_banking_transactions").upsert(row,{onConflict:"user_id,open_banking_account_id,provider_transaction_id",ignoreDuplicates:true}).select().maybeSingle();if(!e&&created)inserted.push({...created,account_id:acc.id,account_name:acc.account_name,iban:acc.iban});}}await admin.from("open_banking_connections").update({status:"LN",last_synced_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",cid).eq("user_id",user.id);return out({connection_id:cid,imported_count:inserted.length,transactions:inserted});}
return out({error:"Unbekannte action",allowed:["institutions","create-requisition","get-accounts","sync"]},400);}catch(e){console.error(e);return out({error:e instanceof Error?e.message:String(e)},500)}});
