import { createClient } from "npm:@supabase/supabase-js@2";
const API="https://api.enablebanking.com";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Content-Type":"application/json"};
const out=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:cors});
function b64u(x:Uint8Array|string){const a=typeof x==='string'?new TextEncoder().encode(x):x;let s='';for(let i=0;i<a.length;i+=0x8000)s+=String.fromCharCode(...a.subarray(i,i+0x8000));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}
function pemBytes(pem:string){const b=pem.replace(/-----BEGIN PRIVATE KEY-----/g,'').replace(/-----END PRIVATE KEY-----/g,'').replace(/\s/g,'');const x=atob(b),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a}
async function jwt(){const kid=Deno.env.get('ENABLE_BANKING_APP_ID'),pem=Deno.env.get('ENABLE_BANKING_PRIVATE_KEY');if(!kid||!pem)throw Error('ENABLE_BANKING_APP_ID / ENABLE_BANKING_PRIVATE_KEY fehlen in Supabase Secrets');const iat=Math.floor(Date.now()/1000);const h=b64u(JSON.stringify({typ:'JWT',alg:'RS256',kid})),p=b64u(JSON.stringify({iss:'enablebanking.com',aud:'api.enablebanking.com',iat,exp:iat+3600}));const key=await crypto.subtle.importKey('pkcs8',pemBytes(pem),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(`${h}.${p}`));return `${h}.${p}.${b64u(new Uint8Array(sig))}`}
async function eb(path:string,init:RequestInit={},req?:Request){const headers=new Headers(init.headers||{});headers.set('Authorization',`Bearer ${await jwt()}`);headers.set('Accept','application/json');if(init.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');if(req){const ua=req.headers.get('user-agent'),lang=req.headers.get('accept-language');if(ua)headers.set('Psu-User-Agent',ua);if(lang)headers.set('Psu-Accept-language',lang)}const r=await fetch(`${API}${path}`,{...init,headers});const t=await r.text();let d:any;try{d=JSON.parse(t)}catch{d={raw:t}}if(!r.ok)throw Error(`${d?.message||d?.detail||d?.error||`Enable Banking HTTP ${r.status}`}${d?.error&&d?.message?` (${d.error})`:''}`);return d}
function iban(a:any){return a?.account_id?.iban||a?.iban||a?.identifications?.find((x:any)=>String(x?.scheme_name||'').toUpperCase()==='IBAN')?.identification||null}
function name(a:any){return a?.name||a?.account_name||a?.account_holder?.name||a?.holder||'Bankkonto'}
function cp(t:any){return t?.creditor?.name||t?.debtor?.name||null}
function desc(t:any){const r=Array.isArray(t?.remittance_information)?t.remittance_information.join(' '):t?.remittance_information;return r||t?.note||cp(t)||'Bankbuchung'}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const auth=req.headers.get('Authorization');if(!auth?.startsWith('Bearer '))return out({error:'Nicht angemeldet'},401);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')||Deno.env.get('SUPABASE_PUBLISHABLE_KEY')||'',service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||Deno.env.get('SUPABASE_SECRET_KEY')||'';if(!service)throw Error('Supabase Service Role Secret fehlt');const uc=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:{user},error}=await uc.auth.getUser();if(error||!user)return out({error:'Ungültige Sitzung'},401);const admin=createClient(url,service),b=await req.json().catch(()=>({})),a=String(b.action||'');
if(a==='application')return out(await eb('/application',{},req));
if(a==='institutions'){const c=String(b.country||'DE').toUpperCase(),d=await eb(`/aspsps?country=${encodeURIComponent(c)}&service=AIS`,{},req);return out((d?.aspsps||[]).map((x:any)=>({id:x.name,name:x.name,country:x.country||c,logo:x.logo?.url||x.logo||x.group?.logo||null,bic:x.bic||x.bic_fi||null,auth_methods:x.auth_methods||[],psu_types:x.psu_types||['personal']})))}
if(a==='create-auth'){const institution=String(b.institution_name||''),country=String(b.country||'DE').toUpperCase(),redirect=String(b.redirect||'');if(!institution||!redirect)return out({error:'Bank oder Redirect URL fehlt'},400);const state=crypto.randomUUID(),d=await eb('/auth',{method:'POST',body:JSON.stringify({access:{balances:true,transactions:true},aspsp:{name:institution,country},state,redirect_url:redirect,psu_type:String(b.psu_type||'personal').toLowerCase(),language:'de',psu_id:user.id})},req);const {data:c,error}=await admin.from('open_banking_connections').insert({user_id:user.id,provider:'enablebanking',authorization_id:d.authorization_id,institution_id:institution,institution_name:institution,institution_logo:b.institution_logo||null,country,state,status:'PENDING_AUTHORIZATION'}).select().single();if(error)throw error;return out({connection_id:c.id,authorization_id:d.authorization_id,url:d.url,state})}
if(a==='complete'){const cid=String(b.connection_id||''),code=String(b.code||''),state=String(b.state||'');if(!cid||!code)return out({error:'Callback-Daten fehlen'},400);const {data:c}=await uc.from('open_banking_connections').select('*').eq('id',cid).eq('user_id',user.id).single();if(!c)return out({error:'Verbindung nicht gefunden'},404);if(c.state&&state&&c.state!==state)return out({error:'Ungültiger Open-Banking-State'},400);const s=await eb('/sessions',{method:'POST',body:JSON.stringify({code})},req);if(!s.session_id)throw Error('Enable Banking hat keine Session-ID zurückgegeben');const sd=await eb(`/sessions/${encodeURIComponent(s.session_id)}`,{},req);for(const id of (sd?.accounts||[])){const d=await eb(`/accounts/${encodeURIComponent(id)}/details`,{},req).catch(()=>({}));const {error}=await admin.from('open_banking_accounts').upsert({user_id:user.id,connection_id:cid,provider_account_id:id,iban:iban(d),account_name:name(d),owner_name:d?.holder||d?.owner_name||null,institution_id:c.institution_id,currency:d?.currency||'EUR',selected:true,updated_at:new Date().toISOString()},{onConflict:'user_id,provider_account_id'});if(error)throw error}await admin.from('open_banking_connections').update({session_id:s.session_id,status:sd.status||'AUTHORIZED',updated_at:new Date().toISOString()}).eq('id',cid).eq('user_id',user.id);const {data:accounts}=await admin.from('open_banking_accounts').select('*').eq('connection_id',cid).eq('user_id',user.id);return out({connection_id:cid,session_id:s.session_id,status:sd.status,accounts:accounts||[]})}
if(a==='sync'){const cid=String(b.connection_id||''),ids=Array.isArray(b.account_ids)?b.account_ids.map(String):[];const {data:c}=await uc.from('open_banking_connections').select('*').eq('id',cid).eq('user_id',user.id).single();if(!c?.session_id)return out({error:'Keine autorisierte Bankverbindung gefunden'},404);const {data:accounts}=await uc.from('open_banking_accounts').select('*').eq('connection_id',cid).eq('user_id',user.id).in('provider_account_id',ids.length?ids:['__none__']);const imported:any[]=[];for(const acc of accounts||[]){try{const bd=await eb(`/accounts/${encodeURIComponent(acc.provider_account_id)}/balances`,{},req);const z=(bd?.balances||[]).find((x:any)=>['CLAV','ITAV','ITBD'].includes(x?.balance_type))||bd?.balances?.[0];if(z?.balance_amount?.amount!=null)await admin.from('open_banking_accounts').update({current_balance:Number(z.balance_amount.amount),updated_at:new Date().toISOString()}).eq('id',acc.id).eq('user_id',user.id)}catch(_){}let cont:string|null=null,guard=0;do{const qs=new URLSearchParams({strategy:'longest'});if(cont)qs.set('continuation_key',cont);const td=await eb(`/accounts/${encodeURIComponent(acc.provider_account_id)}/transactions?${qs}`,{},req);for(const t of td?.transactions||[]){if(t?.status&&t.status!=='BOOK')continue;const n=Number(t?.transaction_amount?.amount);if(!Number.isFinite(n))continue;const signed=String(t?.credit_debit_indicator||'').toUpperCase()==='CRDT'?Math.abs(n):-Math.abs(n);const pid=t?.entry_reference||t?.transaction_id||[t?.booking_date||'',n,desc(t),cp(t)||''].join('|');const row={user_id:user.id,open_banking_account_id:acc.id,provider_transaction_id:pid,booking_date:t?.booking_date||t?.transaction_date||null,value_date:t?.value_date||null,description:desc(t),counterparty:cp(t),amount:signed,currency:t?.transaction_amount?.currency||acc.currency||'EUR',raw:t};const {data:created,error}=await admin.from('open_banking_transactions').upsert(row,{onConflict:'user_id,open_banking_account_id,provider_transaction_id',ignoreDuplicates:true}).select().maybeSingle();if(!error&&created)imported.push({...created,account_id:acc.id,account_name:acc.account_name,iban:acc.iban})}cont=td?.continuation_key||null;guard++}while(cont&&guard<30)}await admin.from('open_banking_connections').update({status:'AUTHORIZED',last_synced_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',cid).eq('user_id',user.id);return out({connection_id:cid,imported_count:imported.length,transactions:imported})}
return out({error:'Unbekannte action',allowed:['application','institutions','create-auth','complete','sync']},400)}catch(e){console.error(e);return out({error:e instanceof Error?e.message:String(e)},500)}});
